    CREATE TABLE IF NOT EXISTS coffee_makers (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        firm VARCHAR(35) NOT NULL,
        model VARCHAR(35) NOT NULL,
        milk_compartment INTEGER NOT NULL,
        sugar_compartment INTEGER NOT NULL,
        water_compartment INTEGER NOT NULL,
        order_timing INTEGER NOT NULL,
        flushing_timing INTEGER NOT NULL,
        turned_on BOOLEAN NOT NULL,
        amount_of_water_for_flushing INTEGER NOT NULL,
        CONSTRAINT pk_coffee_makers PRIMARY KEY (id)
     );


    CREATE TABLE IF NOT EXISTS coffee (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        coffee_type VARCHAR NOT NULL,
        coffee_maker_id BIGINT NOT NULL,
        created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        CONSTRAINT pk_coffee PRIMARY KEY (id),
        CONSTRAINT fk_coffee_on_coffee_makers FOREIGN KEY (coffee_maker_id) REFERENCES coffee_makers (id)
    );


    CREATE TABLE IF NOT EXISTS flushing (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        coffee_maker_id BIGINT NOT NULL,
        start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        CONSTRAINT pk_flushing PRIMARY KEY (id),
        CONSTRAINT fk_flushing_on_coffee_makers FOREIGN KEY (coffee_maker_id) REFERENCES coffee_makers (id)
    );


    CREATE TABLE IF NOT EXISTS milks (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        coffee_maker_id BIGINT NOT NULL,
        fall_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        quantity INTEGER NOT NULL,
        CONSTRAINT pk_milks PRIMARY KEY (id),
        CONSTRAINT fk_milks_on_coffee_makers FOREIGN KEY (coffee_maker_id) REFERENCES coffee_makers (id)
    );


    CREATE TABLE IF NOT EXISTS sugars (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        coffee_maker_id BIGINT NOT NULL,
        fall_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        quantity INTEGER NOT NULL,
        CONSTRAINT pk_sugars PRIMARY KEY (id),
        CONSTRAINT fk_sugars_on_coffee_makers FOREIGN KEY (coffee_maker_id) REFERENCES coffee_makers (id)
    );


    CREATE TABLE IF NOT EXISTS waters (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        coffee_maker_id BIGINT NOT NULL,
        fall_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
        quantity INTEGER NOT NULL,
        CONSTRAINT pk_waters PRIMARY KEY (id),
        CONSTRAINT fk_waters_on_coffee_makers FOREIGN KEY (coffee_maker_id) REFERENCES coffee_makers (id)
    );



